name: CI

# trigger action on all push events
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout repo code, available at $GITHUB_WORKSPACE
    - uses: actions/checkout@v2       
      # Install azure function core tools
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: ls ${{ github.workspace }}
    - run: npm install azure-functions-core-tools@3
      working-directory:  github-branch-protector

  
    # Build function project
    # https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=windows%2Ccsharp%2Cbash#start
    - name: Build function
      run: func start --build --powershell
      env: 
        func: ${{ github.workspace }}/github-branch-protector/node_modules/azure-functions-core-tools/bin
