name: CI

# trigger action on all push events
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Install azure-functions-core-tools@3
    - name: Install Azure Function Core Tools v3
      run: npm install -g azure-functions-core-tools@3
     
    # Build function project
    # https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=windows%2Ccsharp%2Cbash#start
    - name: Build function
      run: func start --build --powershell
